# Generated by Django 6.0.3 on 2026-03-21 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_name', models.CharField(default='Assistant IA', max_length=100)),
                ('greeting_message', models.TextField(default="Bonjour, je suis l'assistant IA, comment puis-je vous aider ?")),
                ('system_prompt', models.TextField(blank=True)),
                ('tone', models.CharField(default='professionnel', max_length=50)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=30)),
                ('enable_sms_summary', models.BooleanField(default=True)),
                ('enable_transcription', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
