# Generated by Django 6.0.3 on 2026-03-21 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='enable_appointment_booking',
            field=models.BooleanField(default=False, help_text="Permet à l'agent de proposer ou prendre des rendez-vous."),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='enable_call_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='enable_human_transfer',
            field=models.BooleanField(default=False, help_text='Permet de transférer vers un humain ou de proposer un rappel.'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='enable_rag',
            field=models.BooleanField(default=True, help_text="Permet à l'agent d'utiliser la base documentaire."),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='enable_sms_followup',
            field=models.BooleanField(default=False, help_text="Permet l'envoi de SMS de suivi après interaction."),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='enable_table_booking',
            field=models.BooleanField(default=False, help_text="Permet à l'agent de gérer des réservations."),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='fallback_message',
            field=models.TextField(blank=True, default="Je n'ai pas cette information pour le moment, mais je peux prendre un message.", help_text="Réponse de secours si l'agent ne sait pas répondre."),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='interruptible',
            field=models.BooleanField(default=True, help_text="Autorise l'appelant à interrompre l'agent pendant qu'il parle."),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='max_call_duration_seconds',
            field=models.PositiveIntegerField(default=600, help_text="Durée maximale d'un appel en secondes."),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='response_style',
            field=models.CharField(blank=True, default='Réponses courtes, naturelles et claires.', help_text="Style global de réponse de l'agent.", max_length=100),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='voice',
            field=models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('sage', 'Sage'), ('verse', 'Verse')], default='alloy', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='tone',
            field=models.CharField(choices=[('professionnel', 'Professionnel'), ('chaleureux', 'Chaleureux'), ('dynamique', 'Dynamique'), ('premium', 'Premium'), ('rassurant', 'Rassurant'), ('direct', 'Direct')], default='professionnel', max_length=50),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('medical', 'Cabinet médical'), ('beauty', 'Beauté / Bien-être'), ('real_estate', 'Immobilier'), ('lawyer', 'Cabinet juridique'), ('plumber', 'Plomberie'), ('electrician', 'Électricité'), ('retail', 'Commerce'), ('agency', 'Agence'), ('other', 'Autre')], default='other', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website_url', models.URLField(blank=True)),
                ('business_description', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('extra_notes', models.TextField(blank=True, help_text="Informations internes utiles à l'agent.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('website', 'Site web'), ('pdf', 'PDF'), ('text', 'Texte libre'), ('faq', 'FAQ')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_pdfs/')),
                ('raw_text', models.TextField(blank=True, help_text="Texte brut fourni directement par l'utilisateur.")),
                ('extracted_text', models.TextField(blank=True, help_text='Texte extrait automatiquement depuis un site ou un PDF.')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('ready', 'Prêt'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('use_ocr', models.BooleanField(default=False, help_text='Indique si une OCR doit être tentée pour ce document.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_key', models.CharField(choices=[('take_message', 'Prendre un message'), ('book_appointment', 'Prendre un rendez-vous'), ('book_table', 'Réserver une table'), ('send_sms', 'Envoyer un SMS'), ('transfer_human', 'Transférer vers un humain'), ('faq_search', 'Rechercher dans la base documentaire')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, help_text="Configuration spécifique de l'outil.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='agents.agentsettings')),
            ],
            options={
                'unique_together': {('agent', 'tool_key')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, help_text='Métadonnées utiles : page, section, url, titre...', null=True)),
                ('embedding', models.JSONField(blank=True, help_text='Embedding stocké en JSON pour une V1 simple.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='agents.knowledgesource')),
            ],
            options={
                'ordering': ['source', 'chunk_index'],
                'unique_together': {('source', 'chunk_index')},
            },
        ),
    ]
