# Generated by Django 6.0.3 on 2026-03-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentsettings_enable_appointment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsettings',
            name='voice',
            field=models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('fable', 'Fable'), ('nova', 'Nova'), ('onyx', 'Onyx'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse'), ('marin', 'Marin'), ('cedar', 'Cedar')], default='alloy', max_length=50),
        ),
    ]
