# Generated by Django 6.0.3 on 2026-03-23 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=64, unique=True)),
                ('stream_sid', models.CharField(blank=True, max_length=64)),
                ('from_number', models.CharField(blank=True, max_length=30)),
                ('to_number', models.CharField(blank=True, max_length=30)),
                ('direction', models.CharField(default='inbound', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('ringing', 'Ça sonne'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('busy', 'Occupé'), ('no_answer', 'Pas de réponse'), ('canceled', 'Annulé')], default='initiated', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('sms_summary_sent', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, help_text="Métadonnées techniques de l'appel.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='agents.agentsettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Appelant'), ('assistant', 'Assistant'), ('system', 'Système'), ('tool', 'Outil')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp_ms', models.PositiveIntegerField(default=0, help_text="Timestamp approximatif dans l'appel en millisecondes.")),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.callsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
