# Generated by Django 6.0.3 on 2026-03-23 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_callsession_callmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentsettings',
            options={'ordering': ['user__email']},
        ),
        migrations.AlterModelOptions(
            name='agenttool',
            options={'ordering': ['tool_key']},
        ),
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterModelOptions(
            name='knowledgechunk',
            options={'ordering': ['source_id', 'chunk_index']},
        ),
        migrations.AlterModelOptions(
            name='knowledgesource',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='inbound_calls_enabled',
            field=models.BooleanField(default=False, help_text='Active réellement la réception des appels entrants pour cet agent.'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='twilio_configured',
            field=models.BooleanField(default=False, help_text='Indique que le numéro Twilio a bien été relié et validé.'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='twilio_phone_sid',
            field=models.CharField(blank=True, default='', help_text='SID du numéro Twilio, utile pour la synchro et le debug.', max_length=64),
        ),
        migrations.AddField(
            model_name='callsession',
            name='end_reason',
            field=models.CharField(blank=True, default='', help_text="Cause technique ou métier de fin d'appel si connue.", max_length=255),
        ),
        migrations.AlterField(
            model_name='agentfeedback',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='response_style',
            field=models.CharField(blank=True, default='Réponses courtes, naturelles et claires.', help_text="Style global de réponse de l'agent.", max_length=255),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='twilio_phone_number',
            field=models.CharField(blank=True, default='', help_text='Numéro Twilio attribué à cet agent, au format international.', max_length=30),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='extra_notes',
            field=models.TextField(blank=True, default='', help_text="Informations internes utiles à l'agent."),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='opening_hours',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Entrant'), ('outbound', 'Sortant')], default='inbound', max_length=20),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='from_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='recording_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='stream_sid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='to_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='extracted_text',
            field=models.TextField(blank=True, default='', help_text='Texte extrait automatiquement depuis un site ou un PDF.'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='raw_text',
            field=models.TextField(blank=True, default='', help_text="Texte brut fourni directement par l'utilisateur."),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='agentfeedback',
            index=models.Index(fields=['user', 'channel'], name='agents_agen_user_id_915c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentfeedback',
            index=models.Index(fields=['user', 'created_at'], name='agents_agen_user_id_d3cd06_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsettings',
            index=models.Index(fields=['twilio_phone_number'], name='agents_agen_twilio__04b36f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsettings',
            index=models.Index(fields=['inbound_calls_enabled'], name='agents_agen_inbound_44d92d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsettings',
            index=models.Index(fields=['twilio_configured'], name='agents_agen_twilio__993554_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttool',
            index=models.Index(fields=['tool_key', 'enabled'], name='agents_agen_tool_ke_23fdbb_idx'),
        ),
        migrations.AddIndex(
            model_name='callmessage',
            index=models.Index(fields=['call_session', 'created_at'], name='agents_call_call_se_1b8175_idx'),
        ),
        migrations.AddIndex(
            model_name='callmessage',
            index=models.Index(fields=['call_session', 'role'], name='agents_call_call_se_89153d_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['user', 'created_at'], name='agents_call_user_id_4e7c89_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['agent', 'created_at'], name='agents_call_agent_i_94bd36_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', 'created_at'], name='agents_call_status_9b6301_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['call_sid'], name='agents_call_call_si_9df5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['stream_sid'], name='agents_call_stream__3c5b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='frequentlyaskedquestion',
            index=models.Index(fields=['user', 'is_active'], name='agents_freq_user_id_edd539_idx'),
        ),
        migrations.AddIndex(
            model_name='frequentlyaskedquestion',
            index=models.Index(fields=['user', 'sort_order'], name='agents_freq_user_id_c68a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['source', 'chunk_index'], name='agents_know_source__d7c6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['user', 'status'], name='agents_know_user_id_af0ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['user', 'source_type'], name='agents_know_user_id_4c957d_idx'),
        ),
    ]
