# Generated by Django 6.0.3 on 2026-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=30)),
                ('caller_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('missed', 'Missed'), ('answered_by_ai', 'Answered by AI'), ('completed', 'Completed')], default='missed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
