# Generated by Django 6.0.3 on 2026-03-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_notes',
            field=models.TextField(blank=True),
        ),
    ]
