# Generated by Django 6.0.3 on 2026-03-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=32)),
                ('prospect_name', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('custom_prompt', models.TextField(blank=True)),
                ('call_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('completed', 'Completed'), ('busy', 'Busy'), ('failed', 'Failed'), ('no-answer', 'No Answer'), ('canceled', 'Canceled'), ('unknown', 'Unknown')], default='initiated', max_length=32)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
